# ==========================
# APPLICATION
# ==========================
spring.application.name=address-service

# ==========================
# SERVER
# ==========================
server.port=8082

# ==========================
# POSTGRESQL DATABASE
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/address_db
spring.datasource.username=postgres
spring.datasource.password=6120
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# EUREKA CLIENT
# ==========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
