server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackUri: forward:/fallback/employee

        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/addresses/**
          filters:
            - name: CircuitBreaker
              args:
                name: ADDRESS-SERVICE
                fallbackUri: forward:/fallback/address

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:

      EMPLOYEE-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      ADDRESS-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  timelimiter:
    instances:

      EMPLOYEE-SERVICE:
        timeoutDuration: 5s

      ADDRESS-SERVICE:
        timeoutDuration: 5s